# Generated by Django 5.0.6 on 2024-06-16 03:40

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
    ]
