# Generated by Django 5.0.6 on 2024-06-16 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone1',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone2',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
